{% set name = "pyudev" %}
{% set version = "0.24.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyudev-{{ version }}.tar.gz
  sha256: 75e54d37218f5ac45b0da1f0fd9cc5e526a3cac3ef1cfad410cf7ab338b01471

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - six

test:
  imports:
    - pyudev
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://pyudev.readthedocs.org/
  summary: A libudev binding
  doc_url: https://pythonhosted.org/pyudev/
  license: LGPL-2.1-only
  license_file: COPYING

extra:
  recipe-maintainers:
    - ruben-arts
