{% set name = "pyudev" %}
{% set version = "0.24.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyudev-{{ version }}.tar.gz
  sha256: 2e945427a21674893bb97632401db62139d91cea1ee96137cc7b07ad22198fc7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - six

test:
  imports:
    - pyudev
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://pyudev.readthedocs.org/
  summary: A libudev binding
  doc_url: https://pythonhosted.org/pyudev/
  license: LGPL-2.1-only
  license_file: COPYING

extra:
  recipe-maintainers:
    - ruben-arts
