{% set name = "pyudev" %}
{% set version = "0.24.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyudev-{{ version }}.tar.gz
  sha256: e788bb983700b1a84efc2e88862b0a51af2a995d5b86bc9997546505cf7b36bc

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - six

test:
  imports:
    - pyudev
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://pyudev.readthedocs.org/
  summary: A libudev binding
  doc_url: https://pythonhosted.org/pyudev/
  license: LGPL-2.1-only
  license_file: COPYING

extra:
  recipe-maintainers:
    - ruben-arts
